version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: typescript
    versions:
    - "< 2.10, >= 2.9.a"
  - dependency-name: typescript
    versions:
    - "< 2.9, >= 2.8.a"
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1101.1
    - 0.1101.2
    - 0.1101.4
    - 0.1102.0
    - 0.1102.1
    - 0.1102.2
    - 0.1102.3
    - 0.1102.4
    - 0.1102.5
    - 0.1102.6
    - 0.1102.7
    - 0.1102.8
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
    - 5.0.0
    - 5.1.0
    - 5.2.0
    - 5.3.0
