webpackJsonp([2,7],{

/***/ 674:
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__angular_core_src_linker_ng_module_factory__ = __webpack_require__(162);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__app_prefs_prefs_module__ = __webpack_require__(710);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2__angular_common_src_common_module__ = __webpack_require__(242);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_3__uirouter_angular_lib_uiRouterNgModule__ = __webpack_require__(164);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_4__angular_forms_src_directives__ = __webpack_require__(243);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_5__angular_forms_src_form_providers__ = __webpack_require__(362);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_6__angular_common_src_localization__ = __webpack_require__(82);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_7__angular_forms_src_directives_radio_control_value_accessor__ = __webpack_require__(84);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_8__gendir_node_modules_uirouter_angular_lib_directives_uiView_ngfactory__ = __webpack_require__(240);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_9__prefs_component_ngfactory__ = __webpack_require__(704);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_10__angular_core_src_i18n_tokens__ = __webpack_require__(159);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_11__app_prefs_prefs_component__ = __webpack_require__(691);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_12__angular_router_src_router_config_loader__ = __webpack_require__(244);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "PrefsModuleNgFactory", function() { return PrefsModuleNgFactory; });
/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};













var PrefsModuleInjector = (function (_super) {
    __extends(PrefsModuleInjector, _super);
    function PrefsModuleInjector(parent) {
        return _super.call(this, parent, [
            __WEBPACK_IMPORTED_MODULE_8__gendir_node_modules_uirouter_angular_lib_directives_uiView_ngfactory__["a" /* UIViewNgFactory */],
            __WEBPACK_IMPORTED_MODULE_9__prefs_component_ngfactory__["a" /* PrefsComponentNgFactory */]
        ], []) || this;
    }
    Object.defineProperty(PrefsModuleInjector.prototype, "_NgLocalization_5", {
        get: function () {
            if ((this.__NgLocalization_5 == null)) {
                (this.__NgLocalization_5 = new __WEBPACK_IMPORTED_MODULE_6__angular_common_src_localization__["a" /* NgLocaleLocalization */](this.parent.get(__WEBPACK_IMPORTED_MODULE_10__angular_core_src_i18n_tokens__["a" /* LOCALE_ID */])));
            }
            return this.__NgLocalization_5;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(PrefsModuleInjector.prototype, "_RadioControlRegistry_6", {
        get: function () {
            if ((this.__RadioControlRegistry_6 == null)) {
                (this.__RadioControlRegistry_6 = new __WEBPACK_IMPORTED_MODULE_7__angular_forms_src_directives_radio_control_value_accessor__["a" /* RadioControlRegistry */]());
            }
            return this.__RadioControlRegistry_6;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(PrefsModuleInjector.prototype, "_UIROUTER_MODULE_TOKEN_7", {
        get: function () {
            if ((this.__UIROUTER_MODULE_TOKEN_7 == null)) {
                (this.__UIROUTER_MODULE_TOKEN_7 = [{ states: [{
                                parent: 'app',
                                name: 'prefs',
                                url: '/prefs',
                                component: __WEBPACK_IMPORTED_MODULE_11__app_prefs_prefs_component__["a" /* PrefsComponent */],
                                data: { requiresAuth: true }
                            }
                        ] }]);
            }
            return this.__UIROUTER_MODULE_TOKEN_7;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(PrefsModuleInjector.prototype, "_ROUTES_8", {
        get: function () {
            if ((this.__ROUTES_8 == null)) {
                (this.__ROUTES_8 = [[{
                            parent: 'app',
                            name: 'prefs',
                            url: '/prefs',
                            component: __WEBPACK_IMPORTED_MODULE_11__app_prefs_prefs_component__["a" /* PrefsComponent */],
                            data: { requiresAuth: true }
                        }
                    ]]);
            }
            return this.__ROUTES_8;
        },
        enumerable: true,
        configurable: true
    });
    PrefsModuleInjector.prototype.createInternal = function () {
        this._CommonModule_0 = new __WEBPACK_IMPORTED_MODULE_2__angular_common_src_common_module__["a" /* CommonModule */]();
        this._UIRouterModule_1 = new __WEBPACK_IMPORTED_MODULE_3__uirouter_angular_lib_uiRouterNgModule__["a" /* UIRouterModule */]();
        this._InternalFormsSharedModule_2 = new __WEBPACK_IMPORTED_MODULE_4__angular_forms_src_directives__["a" /* InternalFormsSharedModule */]();
        this._FormsModule_3 = new __WEBPACK_IMPORTED_MODULE_5__angular_forms_src_form_providers__["a" /* FormsModule */]();
        this._PrefsModule_4 = new __WEBPACK_IMPORTED_MODULE_1__app_prefs_prefs_module__["a" /* PrefsModule */]();
        return this._PrefsModule_4;
    };
    PrefsModuleInjector.prototype.getInternal = function (token, notFoundResult) {
        if ((token === __WEBPACK_IMPORTED_MODULE_2__angular_common_src_common_module__["a" /* CommonModule */])) {
            return this._CommonModule_0;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_3__uirouter_angular_lib_uiRouterNgModule__["a" /* UIRouterModule */])) {
            return this._UIRouterModule_1;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_4__angular_forms_src_directives__["a" /* InternalFormsSharedModule */])) {
            return this._InternalFormsSharedModule_2;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_5__angular_forms_src_form_providers__["a" /* FormsModule */])) {
            return this._FormsModule_3;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_1__app_prefs_prefs_module__["a" /* PrefsModule */])) {
            return this._PrefsModule_4;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_6__angular_common_src_localization__["b" /* NgLocalization */])) {
            return this._NgLocalization_5;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_7__angular_forms_src_directives_radio_control_value_accessor__["a" /* RadioControlRegistry */])) {
            return this._RadioControlRegistry_6;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_3__uirouter_angular_lib_uiRouterNgModule__["c" /* UIROUTER_MODULE_TOKEN */])) {
            return this._UIROUTER_MODULE_TOKEN_7;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_12__angular_router_src_router_config_loader__["a" /* ROUTES */])) {
            return this._ROUTES_8;
        }
        return notFoundResult;
    };
    PrefsModuleInjector.prototype.destroyInternal = function () {
    };
    return PrefsModuleInjector;
}(__WEBPACK_IMPORTED_MODULE_0__angular_core_src_linker_ng_module_factory__["a" /* NgModuleInjector */]));
var PrefsModuleNgFactory = new __WEBPACK_IMPORTED_MODULE_0__angular_core_src_linker_ng_module_factory__["b" /* NgModuleFactory */](PrefsModuleInjector, __WEBPACK_IMPORTED_MODULE_1__app_prefs_prefs_module__["a" /* PrefsModule */]);
//# sourceMappingURL=/Users/cthielen/projects/uirouter/sample-app-ng2/src/prefs.module.ngfactory.js.map

/***/ }),

/***/ 691:
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__global_app_config_service__ = __webpack_require__(64);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return PrefsComponent; });

/**
 * A component which shows and updates app preferences
 */
var PrefsComponent = (function () {
    function PrefsComponent(appConfig) {
        this.appConfig = appConfig;
        this.prefs = {
            restDelay: appConfig.restDelay
        };
    }
    /** Clear out the session storage */
    PrefsComponent.prototype.reset = function () {
        sessionStorage.clear();
        document.location.reload(true);
    };
    /** After saving preferences to session storage, reload the entire application */
    PrefsComponent.prototype.savePrefs = function () {
        Object.assign(this.appConfig, { restDelay: this.prefs.restDelay }).save();
        document.location.reload(true);
    };
    PrefsComponent.ctorParameters = function () { return [{ type: __WEBPACK_IMPORTED_MODULE_0__global_app_config_service__["a" /* AppConfigService */] }]; };
    return PrefsComponent;
}());

//# sourceMappingURL=/Users/cthielen/projects/uirouter/sample-app-ng2/src/prefs.component.js.map

/***/ }),

/***/ 704:
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__app_prefs_prefs_component__ = __webpack_require__(691);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__angular_core_src_linker_view__ = __webpack_require__(51);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__ = __webpack_require__(10);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_3__angular_core_src_metadata_view__ = __webpack_require__(41);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_4__angular_core_src_linker_view_type__ = __webpack_require__(30);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_5__angular_core_src_change_detection_constants__ = __webpack_require__(29);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_6__angular_core_src_linker_component_factory__ = __webpack_require__(34);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_7__app_global_app_config_service__ = __webpack_require__(64);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_8__gendir_node_modules_angular_forms_src_directives_default_value_accessor_ngfactory__ = __webpack_require__(364);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_9__gendir_node_modules_angular_forms_src_directives_ng_model_ngfactory__ = __webpack_require__(366);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_10__gendir_node_modules_angular_forms_src_directives_ng_control_status_ngfactory__ = __webpack_require__(365);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_11__angular_core_src_linker_element_ref__ = __webpack_require__(65);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_12__angular_forms_src_directives_default_value_accessor__ = __webpack_require__(83);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_13__angular_forms_src_directives_control_value_accessor__ = __webpack_require__(24);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_14__angular_forms_src_directives_ng_model__ = __webpack_require__(111);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_15__angular_forms_src_directives_ng_control__ = __webpack_require__(54);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_16__angular_forms_src_directives_ng_control_status__ = __webpack_require__(110);
/* unused harmony export Wrapper_PrefsComponent */
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return PrefsComponentNgFactory; });
/* unused harmony export View_PrefsComponent0 */
/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};

















var Wrapper_PrefsComponent = (function () {
    function Wrapper_PrefsComponent(p0) {
        this._changed = false;
        this.context = new __WEBPACK_IMPORTED_MODULE_0__app_prefs_prefs_component__["a" /* PrefsComponent */](p0);
    }
    Wrapper_PrefsComponent.prototype.ngOnDetach = function (view, componentView, el) {
    };
    Wrapper_PrefsComponent.prototype.ngOnDestroy = function () {
    };
    Wrapper_PrefsComponent.prototype.ngDoCheck = function (view, el, throwOnChange) {
        var changed = this._changed;
        this._changed = false;
        return changed;
    };
    Wrapper_PrefsComponent.prototype.checkHost = function (view, componentView, el, throwOnChange) {
    };
    Wrapper_PrefsComponent.prototype.handleEvent = function (eventName, $event) {
        var result = true;
        return result;
    };
    Wrapper_PrefsComponent.prototype.subscribe = function (view, _eventHandler) {
        this._eventHandler = _eventHandler;
    };
    return Wrapper_PrefsComponent;
}());

var renderType_PrefsComponent_Host = __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__["createRenderComponentType"]('', 0, __WEBPACK_IMPORTED_MODULE_3__angular_core_src_metadata_view__["b" /* ViewEncapsulation */].None, [], {});
var View_PrefsComponent_Host0 = (function (_super) {
    __extends(View_PrefsComponent_Host0, _super);
    function View_PrefsComponent_Host0(viewUtils, parentView, parentIndex, parentElement) {
        return _super.call(this, View_PrefsComponent_Host0, renderType_PrefsComponent_Host, __WEBPACK_IMPORTED_MODULE_4__angular_core_src_linker_view_type__["a" /* ViewType */].HOST, viewUtils, parentView, parentIndex, parentElement, __WEBPACK_IMPORTED_MODULE_5__angular_core_src_change_detection_constants__["b" /* ChangeDetectorStatus */].CheckAlways) || this;
    }
    View_PrefsComponent_Host0.prototype.createInternal = function (rootSelector) {
        this._el_0 = __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__["selectOrCreateRenderHostElement"](this.renderer, 'app-prefs', __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__["EMPTY_INLINE_ARRAY"], rootSelector, null);
        this.compView_0 = new View_PrefsComponent0(this.viewUtils, this, 0, this._el_0);
        this._PrefsComponent_0_3 = new Wrapper_PrefsComponent(this.injectorGet(__WEBPACK_IMPORTED_MODULE_7__app_global_app_config_service__["a" /* AppConfigService */], this.parentIndex));
        this.compView_0.create(this._PrefsComponent_0_3.context);
        this.init(this._el_0, (this.renderer.directRenderer ? null : [this._el_0]), null);
        return new __WEBPACK_IMPORTED_MODULE_6__angular_core_src_linker_component_factory__["a" /* ComponentRef_ */](0, this, this._el_0, this._PrefsComponent_0_3.context);
    };
    View_PrefsComponent_Host0.prototype.injectorGetInternal = function (token, requestNodeIndex, notFoundResult) {
        if (((token === __WEBPACK_IMPORTED_MODULE_0__app_prefs_prefs_component__["a" /* PrefsComponent */]) && (0 === requestNodeIndex))) {
            return this._PrefsComponent_0_3.context;
        }
        return notFoundResult;
    };
    View_PrefsComponent_Host0.prototype.detectChangesInternal = function (throwOnChange) {
        this._PrefsComponent_0_3.ngDoCheck(this, this._el_0, throwOnChange);
        this.compView_0.internalDetectChanges(throwOnChange);
    };
    View_PrefsComponent_Host0.prototype.destroyInternal = function () {
        this.compView_0.destroy();
    };
    View_PrefsComponent_Host0.prototype.visitRootNodesInternal = function (cb, ctx) {
        cb(this._el_0, ctx);
    };
    return View_PrefsComponent_Host0;
}(__WEBPACK_IMPORTED_MODULE_1__angular_core_src_linker_view__["a" /* AppView */]));
var PrefsComponentNgFactory = new __WEBPACK_IMPORTED_MODULE_6__angular_core_src_linker_component_factory__["b" /* ComponentFactory */]('app-prefs', View_PrefsComponent_Host0, __WEBPACK_IMPORTED_MODULE_0__app_prefs_prefs_component__["a" /* PrefsComponent */]);
var styles_PrefsComponent = [];
var renderType_PrefsComponent = __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__["createRenderComponentType"]('', 0, __WEBPACK_IMPORTED_MODULE_3__angular_core_src_metadata_view__["b" /* ViewEncapsulation */].None, styles_PrefsComponent, {});
var View_PrefsComponent0 = (function (_super) {
    __extends(View_PrefsComponent0, _super);
    function View_PrefsComponent0(viewUtils, parentView, parentIndex, parentElement) {
        return _super.call(this, View_PrefsComponent0, renderType_PrefsComponent, __WEBPACK_IMPORTED_MODULE_4__angular_core_src_linker_view_type__["a" /* ViewType */].COMPONENT, viewUtils, parentView, parentIndex, parentElement, __WEBPACK_IMPORTED_MODULE_5__angular_core_src_change_detection_constants__["b" /* ChangeDetectorStatus */].CheckAlways) || this;
    }
    View_PrefsComponent0.prototype.createInternal = function (rootSelector) {
        var parentRenderNode = this.renderer.createViewRoot(this.parentElement);
        this._text_0 = this.renderer.createText(parentRenderNode, '\n    ', null);
        this._el_1 = __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__["createRenderElement"](this.renderer, parentRenderNode, 'div', __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__["EMPTY_INLINE_ARRAY"], null);
        this._text_2 = this.renderer.createText(this._el_1, '\n      ', null);
        this._el_3 = __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__["createRenderElement"](this.renderer, this._el_1, 'button', new __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__["InlineArray2"](2, 'class', 'btn btn-primary'), null);
        this._el_4 = __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__["createRenderElement"](this.renderer, this._el_3, 'i', new __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__["InlineArray2"](2, 'class', 'fa fa-recycle'), null);
        this._text_5 = this.renderer.createText(this._el_3, ' ', null);
        this._el_6 = __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__["createRenderElement"](this.renderer, this._el_3, 'span', __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__["EMPTY_INLINE_ARRAY"], null);
        this._text_7 = this.renderer.createText(this._el_6, 'Reset All Data', null);
        this._text_8 = this.renderer.createText(this._el_1, '\n    ', null);
        this._text_9 = this.renderer.createText(parentRenderNode, '\n    \n    ', null);
        this._el_10 = __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__["createRenderElement"](this.renderer, parentRenderNode, 'div', __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__["EMPTY_INLINE_ARRAY"], null);
        this._text_11 = this.renderer.createText(this._el_10, '\n      ', null);
        this._el_12 = __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__["createRenderElement"](this.renderer, this._el_10, 'label', new __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__["InlineArray2"](2, 'for', 'restDelay'), null);
        this._text_13 = this.renderer.createText(this._el_12, 'Simulated REST API delay (ms)', null);
        this._text_14 = this.renderer.createText(this._el_10, '\n      ', null);
        this._el_15 = __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__["createRenderElement"](this.renderer, this._el_10, 'input', new __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__["InlineArray4"](4, 'name', 'restDelay', 'type', 'text'), null);
        this._DefaultValueAccessor_15_3 = new __WEBPACK_IMPORTED_MODULE_8__gendir_node_modules_angular_forms_src_directives_default_value_accessor_ngfactory__["a" /* Wrapper_DefaultValueAccessor */](this.renderer, new __WEBPACK_IMPORTED_MODULE_11__angular_core_src_linker_element_ref__["a" /* ElementRef */](this._el_15));
        this._NG_VALUE_ACCESSOR_15_4 = [this._DefaultValueAccessor_15_3.context];
        this._NgModel_15_5 = new __WEBPACK_IMPORTED_MODULE_9__gendir_node_modules_angular_forms_src_directives_ng_model_ngfactory__["a" /* Wrapper_NgModel */](null, null, null, this._NG_VALUE_ACCESSOR_15_4);
        this._NgControl_15_6 = this._NgModel_15_5.context;
        this._NgControlStatus_15_7 = new __WEBPACK_IMPORTED_MODULE_10__gendir_node_modules_angular_forms_src_directives_ng_control_status_ngfactory__["a" /* Wrapper_NgControlStatus */](this._NgControl_15_6);
        this._text_16 = this.renderer.createText(this._el_10, '\n      ', null);
        this._el_17 = __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__["createRenderElement"](this.renderer, this._el_10, 'button', new __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__["InlineArray2"](2, 'class', 'btn btn-primary'), null);
        this._text_18 = this.renderer.createText(this._el_17, 'Save', null);
        this._text_19 = this.renderer.createText(this._el_10, '\n    ', null);
        this._text_20 = this.renderer.createText(parentRenderNode, '\n', null);
        var disposable_0 = __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__["subscribeToRenderElement"](this, this._el_3, new __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__["InlineArray2"](2, 'click', null), this.eventHandler(this.handleEvent_3));
        var disposable_1 = __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__["subscribeToRenderElement"](this, this._el_15, new __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__["InlineArray8"](6, 'ngModelChange', null, 'input', null, 'blur', null), this.eventHandler(this.handleEvent_15));
        this._NgModel_15_5.subscribe(this, this.eventHandler(this.handleEvent_15), true);
        var disposable_2 = __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__["subscribeToRenderElement"](this, this._el_17, new __WEBPACK_IMPORTED_MODULE_2__angular_core_src_linker_view_utils__["InlineArray2"](2, 'click', null), this.eventHandler(this.handleEvent_17));
        this.init(null, (this.renderer.directRenderer ? null : [
            this._text_0,
            this._el_1,
            this._text_2,
            this._el_3,
            this._el_4,
            this._text_5,
            this._el_6,
            this._text_7,
            this._text_8,
            this._text_9,
            this._el_10,
            this._text_11,
            this._el_12,
            this._text_13,
            this._text_14,
            this._el_15,
            this._text_16,
            this._el_17,
            this._text_18,
            this._text_19,
            this._text_20
        ]), [
            disposable_0,
            disposable_1,
            disposable_2
        ]);
        return null;
    };
    View_PrefsComponent0.prototype.injectorGetInternal = function (token, requestNodeIndex, notFoundResult) {
        if (((token === __WEBPACK_IMPORTED_MODULE_12__angular_forms_src_directives_default_value_accessor__["a" /* DefaultValueAccessor */]) && (15 === requestNodeIndex))) {
            return this._DefaultValueAccessor_15_3.context;
        }
        if (((token === __WEBPACK_IMPORTED_MODULE_13__angular_forms_src_directives_control_value_accessor__["a" /* NG_VALUE_ACCESSOR */]) && (15 === requestNodeIndex))) {
            return this._NG_VALUE_ACCESSOR_15_4;
        }
        if (((token === __WEBPACK_IMPORTED_MODULE_14__angular_forms_src_directives_ng_model__["a" /* NgModel */]) && (15 === requestNodeIndex))) {
            return this._NgModel_15_5.context;
        }
        if (((token === __WEBPACK_IMPORTED_MODULE_15__angular_forms_src_directives_ng_control__["a" /* NgControl */]) && (15 === requestNodeIndex))) {
            return this._NgControl_15_6;
        }
        if (((token === __WEBPACK_IMPORTED_MODULE_16__angular_forms_src_directives_ng_control_status__["a" /* NgControlStatus */]) && (15 === requestNodeIndex))) {
            return this._NgControlStatus_15_7.context;
        }
        return notFoundResult;
    };
    View_PrefsComponent0.prototype.detectChangesInternal = function (throwOnChange) {
        this._DefaultValueAccessor_15_3.ngDoCheck(this, this._el_15, throwOnChange);
        var currVal_15_1_0 = 'restDelay';
        this._NgModel_15_5.check_name(currVal_15_1_0, throwOnChange, false);
        var currVal_15_1_1 = this.context.prefs.restDelay;
        this._NgModel_15_5.check_model(currVal_15_1_1, throwOnChange, false);
        this._NgModel_15_5.ngDoCheck(this, this._el_15, throwOnChange);
        this._NgControlStatus_15_7.ngDoCheck(this, this._el_15, throwOnChange);
        this._NgControlStatus_15_7.checkHost(this, this, this._el_15, throwOnChange);
    };
    View_PrefsComponent0.prototype.destroyInternal = function () {
        this._NgModel_15_5.ngOnDestroy();
    };
    View_PrefsComponent0.prototype.handleEvent_3 = function (eventName, $event) {
        this.markPathToRootAsCheckOnce();
        var result = true;
        if ((eventName == 'click')) {
            var pd_sub_0 = (this.context.reset() !== false);
            result = (pd_sub_0 && result);
        }
        return result;
    };
    View_PrefsComponent0.prototype.handleEvent_15 = function (eventName, $event) {
        this.markPathToRootAsCheckOnce();
        var result = true;
        result = (this._DefaultValueAccessor_15_3.handleEvent(eventName, $event) && result);
        if ((eventName == 'ngModelChange')) {
            var pd_sub_0 = ((this.context.prefs.restDelay = $event) !== false);
            result = (pd_sub_0 && result);
        }
        return result;
    };
    View_PrefsComponent0.prototype.handleEvent_17 = function (eventName, $event) {
        this.markPathToRootAsCheckOnce();
        var result = true;
        if ((eventName == 'click')) {
            var pd_sub_0 = (this.context.savePrefs() !== false);
            result = (pd_sub_0 && result);
        }
        return result;
    };
    return View_PrefsComponent0;
}(__WEBPACK_IMPORTED_MODULE_1__angular_core_src_linker_view__["a" /* AppView */]));

//# sourceMappingURL=/Users/cthielen/projects/uirouter/sample-app-ng2/src/prefs.component.ngfactory.js.map

/***/ }),

/***/ 710:
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return PrefsModule; });
var PrefsModule = (function () {
    function PrefsModule() {
    }
    return PrefsModule;
}());

//# sourceMappingURL=/Users/cthielen/projects/uirouter/sample-app-ng2/src/prefs.module.js.map

/***/ })

});
//# sourceMappingURL=2.chunk.js.map